### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by pablodawson** [yuyanli0831/OmniFusion#2]
Hello, 
Appreciate your work on this.
Do you by chance have a script to do inference on custom images?

On other note, I tried to load the weights you provided: 

```
ckpt = torch.load('./checkpoints/Stanford_2iter.pth')
network.load_state_dict(ckpt)
```

With the pretrained model of both Datasets. None detected the weights:
```
Error(s) in loading state_dict for spherical_fusion:
Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias" (...)
```
Thanks in advance.

**Comment by yuyanli0831** [comment]
A reason could be that I used nn.Parallel during both training/inference. You can enable nn.Parallel as well (even with a single GPU).

**Comment by pablodawson** [comment]
That was it, thanks. I had to modify the layer "down1" for it to work too. You had the correct sized one commented out.

**Comment by pablodawson** [comment]
![test_equi_pred_0](https://user-images.githubusercontent.com/74978011/173409404-e40d7d7a-11b3-423e-8628-02c850ca56b9.png)
Managed to do inference on a custom image but the patches are very visible. Could be a problem with the fusion layer?

**Comment by jiayaozhang** [comment]
Hi, I have tried the Stanford2D3D datasets, and also get the similar results. It looks really weird, the patches are very visible

Any help?

![test_equi_pred_0](https://user-images.githubusercontent.com/38579506/187222234-a06773a6-2945-41dd-b1e7-a15beee563b0.png)

This is the test_equi_pred_0.png and I turn the color to gray.

**Comment by MertCokelek** [comment]
> Hi, I have tried the Stanford2D3D datasets, and also get the similar results. It looks really weird, the patches are very visible
> 
> Any help?
> 
> ![test_equi_pred_0](https://user-images.githubusercontent.com/38579506/187222234-a06773a6-2945-41dd-b1e7-a15beee563b0.png)
> 
> This is the test_equi_pred_0.png and I turn the color to gray.

I have the same issue. We might need to run iterative refining step as well.
\

**Comment by yuyanli0831** [comment]
> Hi, I have tried the Stanford2D3D datasets, and also get the similar results. It looks really weird, the patches are very visible
> 
> Any help?
> 
> ![test_equi_pred_0](https://user-images.githubusercontent.com/38579506/187222234-a06773a6-2945-41dd-b1e7-a15beee563b0.png)
> 
> This is the test_equi_pred_0.png and I turn the color to gray.

You can run the iterative refining it could help with the fusion artifacts. Another reason is that our previous learnable fusion layer is still immature. We would like to improve it and make it more efficient and effective.

**Comment by yuyanli0831** [comment]
> ![test_equi_pred_0](https://user-images.githubusercontent.com/74978011/173409404-e40d7d7a-11b3-423e-8628-02c850ca56b9.png) Managed to do inference on a custom image but the patches are very visible. Could be a problem with the fusion layer?

When inferring on a custom dataset, this happens because of the geometric layer (it is trained on a dataset with a different distribution/resolution/scene) is not well tuned for this dataset). We did not provide the learnable fusion layer so far to make the results look seamlessly fused. We would like to improve it and make it more efficient and mature.

**Comment by yuliangguo** [comment]
> 
@pablodawson @MertCokelek @jiayaozhang Thanks for your detailed investigation. The shown visual flaws are somehow as expected, especially for those novel data. Since our current fusion method is still depending on the training data,  how to generalize it customized or novel data is still an open challenge. Although we achieved good evaluation results on those major public datasets, we also found the current method not able to completely removing the artifacts caused by patch-wise discrepancy, especially in a cross-domain setup.  We will be thrilled to see our framework stimulate others' future work to push the frontier of 360 field!
